Update evidence-table-effectiveness.tsx
CyberAgentAILab/EBPMDB pull request #54
Opened 2022-10-25 08:32 UTC by takaakikeda

分からないなりに効果の種類について、5種類に分けてみました。

2022-10-25 23:57 UTC, HirotakeIto requested changes

2022-10-25 23:57 UTC, HirotakeIto commented on components/evidence-table-effectiveness.tsx
> +      case '効果あり(良い効果)':
現状各々のmarkdownのheaderの`'効果あり'`という文字列をkeyにして色を割り当てているので、`'効果あり' `caseを消滅させると、colorのfetchに失敗しちゃわないでしょうか？

`'効果あり'`のcaseは残しつつ、今後新しくdocumentをつくるときはそのようなものはレビューで弾くと言う運用が良さそうに思っています

2022-10-26 06:33 UTC, daimoriwaki commented on components/evidence-table-effectiveness.tsx
> +      case '効果あり(良い効果)':
悪い効果って例が少ないと思うので、'効果あり'は残しつつ、効果あり（悪い効果）を追加するとかでもいいかも？

2022-10-27 07:52 UTC, takaakikeda commented on components/evidence-table-effectiveness.tsx
> +      case '効果あり(良い効果)':
@daimoriwaki さんの意見に賛成です。

2022-10-28 03:15 UTC, daimoriwaki commented on components/evidence-table-effectiveness.tsx
> +      case '効果あり(良い効果)':
そしたらその方針で修正お願いできますか？

2022-10-28 04:36 UTC, daimoriwaki commented on components/evidence-table-effectiveness.tsx
> +      case '効果あり(良い効果)':
#53

2022-11-17 05:34 UTC, closed without merging